name = "smartcampus-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "http://localhost:5000/api/v1"

# Trigger Cloudflare Pages production deployment
