import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import collegeRoutes from './college.routes';
import adminRoutes from './admin.routes';
import collegeAdminRoutes from './collegeAdmin.routes';
import departmentRoutes from './department.routes';
import courseRoutes from './course.routes';
import semesterRoutes from './semester.routes';
import studentRoutes from './student.routes';
import facultyRoutes from './faculty.routes';
import subjectRoutes from './subject.routes';
import attendanceRoutes from './attendance.routes';
import classroomRoutes from './classroom.routes';
import timetableRoutes from './timetable.routes';
import financeRoutes from './finance.routes';
import examRoutes from './exam.routes';
import libraryRoutes from './library.routes';
import parentRoutes from './parent.routes';
import notificationRoutes from './notification.routes';
import reportRoutes from './report.routes';
import saasRoutes from './saas.routes';
import aiRoutes from './ai.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/colleges', collegeRoutes);
router.use('/admin', adminRoutes);
router.use('/college-admin', collegeAdminRoutes);
router.use('/departments', departmentRoutes);
router.use('/courses', courseRoutes);
router.use('/semesters', semesterRoutes);
router.use('/students', studentRoutes);
router.use('/faculty', facultyRoutes);
router.use('/subjects', subjectRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/classrooms', classroomRoutes);
router.use('/timetable', timetableRoutes);
router.use('/finance', financeRoutes);
router.use('/exams', examRoutes);
router.use('/library', libraryRoutes);
router.use('/parent', parentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
router.use('/saas', saasRoutes);
router.use('/ai', aiRoutes);

export default router;
