export type AIMessageSender = 'USER' | 'ASSISTANT' | 'SYSTEM';

export const AIMessageSender = {
  USER: 'USER' as AIMessageSender,
  ASSISTANT: 'ASSISTANT' as AIMessageSender,
  SYSTEM: 'SYSTEM' as AIMessageSender
};

export type AIFeatureKey = 
  | 'CHATBOT'
  | 'STUDENT_PERFORMANCE_PREDICTION'
  | 'ATTENDANCE_INSIGHTS'
  | 'FEE_INSIGHTS'
  | 'TIMETABLE_ASSISTANT'
  | 'EXAM_INSIGHTS'
  | 'NOTIFICATION_GENERATOR'
  | 'REPORT_SUMMARIZER'
  | 'NATURAL_LANGUAGE_SEARCH'
  | 'ANALYTICS_ASSISTANT';

export const AIFeatureKey = {
  CHATBOT: 'CHATBOT' as AIFeatureKey,
  STUDENT_PERFORMANCE_PREDICTION: 'STUDENT_PERFORMANCE_PREDICTION' as AIFeatureKey,
  ATTENDANCE_INSIGHTS: 'ATTENDANCE_INSIGHTS' as AIFeatureKey,
  FEE_INSIGHTS: 'FEE_INSIGHTS' as AIFeatureKey,
  TIMETABLE_ASSISTANT: 'TIMETABLE_ASSISTANT' as AIFeatureKey,
  EXAM_INSIGHTS: 'EXAM_INSIGHTS' as AIFeatureKey,
  NOTIFICATION_GENERATOR: 'NOTIFICATION_GENERATOR' as AIFeatureKey,
  REPORT_SUMMARIZER: 'REPORT_SUMMARIZER' as AIFeatureKey,
  NATURAL_LANGUAGE_SEARCH: 'NATURAL_LANGUAGE_SEARCH' as AIFeatureKey,
  ANALYTICS_ASSISTANT: 'ANALYTICS_ASSISTANT' as AIFeatureKey
};
